import { type LeadRecord } from './pipeline';

export const demoLeads: LeadRecord[] = [
  {
    id: 'lead-1004',
    name: 'Aiden Pillay',
    email: 'aiden.pillay@example.com',
    phone: '+27 82 444 0104',
    intent: 'viewing',
    status: 'new',
    quality: 'clean',
    listingTitle: 'Modern 3-bedroom house in Sandton',
    listingSlug: 'modern-3-bedroom-house-in-sandton-12345',
    agent: 'Lerato Mokoena',
    agency: 'Proppd Verified Realty',
    sourcePage: '/property/modern-3-bedroom-house-in-sandton-12345',
    createdAt: '2026-05-18T14:18:00.000Z',
    message: 'Can I view this property after work this week?',
    flags: [],
  },
  {
    id: 'lead-1003',
    name: 'Thandi van Wyk',
    email: 'thandi.vw@example.com',
    phone: '+27 83 221 4430',
    intent: 'finance',
    status: 'qualified',
    quality: 'clean',
    listingTitle: 'Family townhouse in Umhlanga',
    listingSlug: 'family-townhouse-in-umhlanga-77120',
    agent: 'Aiden Naidoo',
    agency: 'Coastal Living',
    sourcePage: '/property/family-townhouse-in-umhlanga-77120',
    createdAt: '2026-05-18T12:05:00.000Z',
    message: 'I am pre-approved and would like the finance partner details.',
    flags: [],
  },
  {
    id: 'lead-1002',
    name: 'Marius Botha',
    email: 'marius.botha@example.com',
    phone: '+27 84 900 2011',
    intent: 'more_info',
    status: 'contacted',
    quality: 'duplicate',
    listingTitle: 'Sea Point apartment with secure parking',
    listingSlug: 'sea-point-apartment-with-parking-20401',
    agent: 'Mia Jacobs',
    agency: 'Atlantic Property Co.',
    sourcePage: '/property/sea-point-apartment-with-parking-20401',
    createdAt: '2026-05-18T09:40:00.000Z',
    message: 'Please confirm lease terms and whether the parking bay is included.',
    flags: ['duplicate-enquiry'],
  },
  {
    id: 'lead-1001',
    name: 'SEO Partner',
    email: 'promo@example.net',
    phone: '+27 11 000 0000',
    intent: 'more_info',
    status: 'new',
    quality: 'flagged',
    listingTitle: 'Modern 3-bedroom house in Sandton',
    listingSlug: 'modern-3-bedroom-house-in-sandton-12345',
    agent: 'Lerato Mokoena',
    agency: 'Proppd Verified Realty',
    sourcePage: '/list-with-us',
    createdAt: '2026-05-17T16:22:00.000Z',
    message: 'Guaranteed SEO and crypto investment traffic for your portal.',
    flags: ['spam-keyword'],
  },
];
