import type { Listing } from './demo-data';

export const sakstonsAgents = [
  { name: 'Graham Donald', agency: 'Sakstons', area: 'Fourways, Kyalami and Sandton precincts', listings: 6 },
  { name: 'Hamez Saks', agency: 'Sakstons', area: 'Fourways, Kyalami and Sandton precincts', listings: 0 },
  { name: 'Liz Marx', agency: 'Sakstons', area: 'Fourways, Kyalami and Sandton precincts', listings: 12 },
  { name: 'Mark Chait', agency: 'Sakstons', area: 'Fourways, Kyalami and Sandton precincts', listings: 20 },
].map((agent) => ({ ...agent, isActive: true, isVerified: true }));

export const sakstonsAgencies = [
  { name: 'Sakstons', city: 'Sandton', agents: 4, listings: 38 },
].map((agency) => ({ ...agency, isActive: true }));

const sakstonsListingSeed = [
  {
    id: 'sakstons-22450',
    slug: "sakstons-villa-lane-292-bryanston-drive",
    purpose: "For sale",
    title: "Villa Lane – 292 Bryanston Drive",
    location: "Bryanston, Sandton",
    suburb: "Bryanston",
    city: "Sandton",
    province: "Gauteng",
    price: "R 3 299 000",
    priceValue: 3299000,
    beds: 3,
    baths: 4,
    parking: 2,
    type: "Cluster",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2026/03/unit-17-292-Bryanston-Dr-Bryanston-Marc-Saktons-L26.jpg", alt: "Villa Lane – 292 Bryanston Drive - Sakstons source image" }],
    description: "Stunning Three-Level Townhouse in Bryanston This immaculate three-level townhouse offers modern, secure living in a prime Bryanston estate, ideal for couples or young families. Features include: Secure estate with front-door security gate Double garage with laundry and extra storage Domestic Quarters with bathroom and ",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 250,
    erfSize: undefined,
    featured: true,
  },
  {
    id: 'sakstons-22376',
    slug: "sakstons-insignia-luxury-apartments",
    purpose: "To rent",
    title: "Insignia Luxury Apartments",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 17 000 pm",
    priceValue: 17000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2025/05/1.jpg", alt: "Insignia Luxury Apartments - Sakstons source image" }],
    description: "Immaculate, Fully-Furnished Unit with Private Garden – Ready to Move In (Sandown) Wake up in quiet, leafy Sandown just minutes from Sandton’s energy – this modern, move-in ready apartment offers a rare balance of sanctuary and connectedness, designed for both ease and enjoyment. Fully furnished and low maintenance, thi",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 106,
    erfSize: undefined,
    featured: true,
  },
  {
    id: 'sakstons-21622',
    slug: "sakstons-3-bedrooom-ultra-modern-cluster-in-bryanston",
    purpose: "For sale",
    title: "Ultra Modern Cluster In Bryanston",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 3 300 000",
    priceValue: 3300000,
    beds: 3,
    baths: 4,
    parking: 0,
    type: "Cluster",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2024/05/1-1.jpg", alt: "Ultra Modern Cluster In Bryanston - Sakstons source image" }],
    description: "Introducing an exceptional 3-bedroom family home. This exquisite residence seamlessly marries contemporary design with comfort and opulence, boasting impeccable craftsmanship evident in every detail. From the tiled living areas to the elegant wooden floors adorning the bedrooms, every aspect of this home exudes sophist",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 150,
    erfSize: undefined,
    featured: true,
  },
  {
    id: 'sakstons-21604',
    slug: "sakstons-4-bedroom-cluster-sunninghill-gardens",
    purpose: "For sale",
    title: "4 Bedroom Cluster – Sunninghill Gardens",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 2 100 000",
    priceValue: 2100000,
    beds: 4,
    baths: 2,
    parking: 0,
    type: "Cluster",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2024/05/1.jpg", alt: "4 Bedroom Cluster – Sunninghill Gardens - Sakstons source image" }],
    description: "Perfectly arranged, pristine, airy and secure enclave nestled in the heart of Sunninghill Gardens. Ideal for a family, this residence boasts ample, open-plan living spaces flooded with natural light and seamless transitions. Featuring a open-plan kitchen and lounge area. The expansive lounge and dining area effortlessl",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 250,
    erfSize: undefined,
    featured: true,
  },
  {
    id: 'sakstons-20930',
    slug: "sakstons-munyaka-lifestyle-estate-waterfall-city",
    purpose: "To rent",
    title: "Munyaka Lifestyle Estate – Waterfall City",
    location: "Midrand, Midrand",
    suburb: "Midrand",
    city: "Midrand",
    province: "Gauteng",
    price: "R 17 000 pm",
    priceValue: 17000,
    beds: 3,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2024/01/20220307_143745_resized.jpg", alt: "Munyaka Lifestyle Estate – Waterfall City - Sakstons source image" }],
    description: "Experience luxury living in this ground floor apartment featuring three bedrooms with tastefully tiled floors, built-in cupboards, and two well-appointed bathrooms. The ensuite boasts a spacious shower, while the guest bathroom offers both a shower and a bathtub. Upon entering, you’ll find an inviting space that seamle",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 120,
    erfSize: undefined,
    featured: true,
  },
  {
    id: 'sakstons-20518',
    slug: "sakstons-portman-place-two-bedroom-two-bathroom-apartment-in-melrose",
    purpose: "For sale",
    title: "Portman Place – Two Bedroom, Two Bathroom Apartment In Melrose",
    location: "Melrose, Johannesburg",
    suburb: "Melrose",
    city: "Johannesburg",
    province: "Gauteng",
    price: "R 2 500 000",
    priceValue: 2500000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/10/6-1.jpg", alt: "Portman Place – Two Bedroom, Two Bathroom Apartment In Melrose - Sakstons source image" }],
    description: "This gorgeous and newly renovated apartment is for sale in Portman Place, featuring a modern kitchen with an island. Two spacious bedrooms with built in cupboards and tiled flooring, two bathroom one being an en-suite to the main, open plan kitchen leading into an open plan dining and lounge area, which in turn leads t",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 111,
    erfSize: undefined,
    featured: true,
  },
  {
    id: 'sakstons-20461',
    slug: "sakstons-glendouglas-complex-douglasdale-townhouse",
    purpose: "To rent",
    title: "GlenDouglas Complex – Douglasdale – Townhouse",
    location: "Douglasdale, Sandton",
    suburb: "Douglasdale",
    city: "Sandton",
    province: "Gauteng",
    price: "R 17 000 pm",
    priceValue: 17000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Cluster",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/10/1.jpg", alt: "GlenDouglas Complex – Douglasdale – Townhouse - Sakstons source image" }],
    description: "Nestled in the heart of Douglasdale, this charming 2-bedroom, 2-bathroom townhouse presents a unique blend of modern comfort and convenient living. Located within a serene and well-maintained complex, this townhouse offers a peaceful retreat from the bustle of city life while providing easy access to urban amenities. S",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 220,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-20410',
    slug: "sakstons-77-on-grayston-modern-2-bed-2-bath-apartment",
    purpose: "To rent",
    title: "77 on Grayston – Modern 2 Bed 2 Bath – Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 12 000 pm",
    priceValue: 12000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/10/Screenshot-2023-10-16-084913.png", alt: "77 on Grayston – Modern 2 Bed 2 Bath – Apartment - Sakstons source image" }],
    description: "2 bedroom apartment available for rent in the heart of Sandton CBD’s vibrant Hub. This unit is situated on the second floor and boasts a beautiful, expansive 114sqm space. The apartment features two bedrooms with elegant wooden flooring, accompanied by two full bathrooms, each en-suite. The kitchen is equipped with sle",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 114,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-20395',
    slug: "sakstons-baldersani-2-bed-1-bath-garden-apartment",
    purpose: "To rent",
    title: "Baldersani – 2 bed 1 bath – Garden Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 9 500 pm",
    priceValue: 9500,
    beds: 2,
    baths: 1,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/10/Screenshot-2023-10-05-113809.png", alt: "Baldersani – 2 bed 1 bath – Garden Apartment - Sakstons source image" }],
    description: "Modern 2 Bedroom, 1 Bathroom Garden Apartment in Sunninghill This inviting 2-bedroom, 1-bathroom garden apartment in Sunninghill offers a spacious and contemporary living space! Features: • The living area is beautifully tiled and features stackable doors that open to a covered patio, providing a seamless transition to",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 94,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-20007',
    slug: "sakstons-georgian-terrace-2-bed-2-bath-garden-apartment-morningside",
    purpose: "To rent",
    title: "Georgian Terrace – 2 Bed 2 Bath – Garden Apartment – Morningside",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 10 750 pm",
    priceValue: 10750,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/08/20230803_143240_resized.jpg", alt: "Georgian Terrace – 2 Bed 2 Bath – Garden Apartment – Morningside - Sakstons source image" }],
    description: "This stunning and spacious two-bedroom apartment in Morningside features a well-equipped kitchen with built-in cupboards, a pantry cupboard, microwave oven nook, double basin, and space for under-counter appliances, oven, and gas stove. The living area is generously sized and connects to a covered balcony through doubl",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 110,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-19275',
    slug: "sakstons-luxury-living-in-monaco-superb-penthouse-in-fontvieille-with-panoramic-sea-view",
    purpose: "For sale",
    title: "Luxury Living in Monaco: Superb Penthouse in Fontvieille with Panoramic Sea View",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 26 500 000",
    priceValue: 26500000,
    beds: 3,
    baths: 3,
    parking: 2,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Graham Donald",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/04/pic1Monaco.jpg", alt: "Luxury Living in Monaco: Superb Penthouse in Fontvieille with Panoramic Sea View - Sakstons source image" }],
    description: "This is a luxurious penthouse apartment located in the Port of Fontvieille, offering a panoramic view of the marina. It has been completely renovated using high-quality materials and is furnished with branded furniture. The apartment is in a unique position and is not overlooked, ensuring privacy and exclusivity. The a",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 508,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-19242',
    slug: "sakstons-rental-three-bedroom-two-bathroom-apartment-in-sandown",
    purpose: "To rent",
    title: "Rental: Three Bedroom Two Bathroom Apartment in Sandown",
    location: "Sandown, Sandton",
    suburb: "Sandown",
    city: "Sandton",
    province: "Gauteng",
    price: "R 13 000 pm",
    priceValue: 13000,
    beds: 0,
    baths: 0,
    parking: 2,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/03/1.jpg", alt: "Rental: Three Bedroom Two Bathroom Apartment in Sandown - Sakstons source image" }],
    description: "This newly renovated top floor apartment is in the well-maintained complex of Sandown Palms. Perfectly located close to Mandela Square, Sandton City and the Gautrain station, highway and other amenities. Very safe and secure Three spacious bedrooms with ample cupboards and laminated flooring Two bathrooms with one bein",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 95,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-19241',
    slug: "sakstons-santana-sunninghill-3-bed-cluster",
    purpose: "To rent",
    title: "Santana Sunninghill – 3 Bed Cluster",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 23 000 pm",
    priceValue: 23000,
    beds: 3,
    baths: 3,
    parking: 2,
    type: "Property",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/03/20220512_150126.jpg", alt: "Santana Sunninghill – 3 Bed Cluster - Sakstons source image" }],
    description: "3 bed 3 bath double storey townhouse. Neat and spacious double story stand alone a must see. Open plan lounge, dining room and kitchen. Lounge opens out onto a covered patio and a very large easy to maintain garden with perfect sized sparkling pool. downstairs study room and domestic quarters aircon in all the rooms la",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 200,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-19205',
    slug: "sakstons-rental-the-avenues-on-broadacres-three-bedroom-cluster",
    purpose: "To rent",
    title: "Rental: The Avenues On Broadacres, Three Bedroom Cluster",
    location: "Broadacres, Sandton",
    suburb: "Broadacres",
    city: "Sandton",
    province: "Gauteng",
    price: "R 25 000 pm",
    priceValue: 25000,
    beds: 3,
    baths: 2,
    parking: 2,
    type: "Cluster",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/03/property-9404819-75808182_sd.jpg", alt: "Rental: The Avenues On Broadacres, Three Bedroom Cluster - Sakstons source image" }],
    description: "This modern gem is situated in the beautiful complex of The Avenues in Broadacres. Downstairs features an open plan lounge area leading out to a private patio with build in braai and private garden with a swimming pool; modern kitchen, dining area, guest toilet and fully automated double garage. Upstairs features three",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 110,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-19169',
    slug: "sakstons-the-kanyin-2-bed-1-bath-middle-floor-apartment-2",
    purpose: "To rent",
    title: "The Kanyin – 2 bed 1 bath – Middle Floor Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 9 000 pm",
    priceValue: 9000,
    beds: 2,
    baths: 1,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/03/Capture.jpg", alt: "The Kanyin – 2 bed 1 bath – Middle Floor Apartment - Sakstons source image" }],
    description: "The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in Braai. • KITCHEN: Open plan, granite tops, plenty of built-in cupbo",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 91,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18926',
    slug: "sakstons-the-kanyin-2-bed-2-bath-garden-apartment-2",
    purpose: "For sale",
    title: "The Kanyin – 2 Bed 2 Bath – Garden Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 1 400 000",
    priceValue: 1400000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/02/pic_33282230_640x480.jpg", alt: "The Kanyin – 2 Bed 2 Bath – Garden Apartment - Sakstons source image" }],
    description: "The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in braai with PET FRIENDLY garden. • KITCHEN: Open plan, granite tops,",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 94,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18859',
    slug: "sakstons-kalgaro-estate-2-bed-1-bath-middle-floor-apartment",
    purpose: "To rent",
    title: "Kalgaro Estate – 2 Bed 1 Bath – Middle Floor Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 7 750 pm",
    priceValue: 7750,
    beds: 2,
    baths: 1,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/02/01.jpg", alt: "Kalgaro Estate – 2 Bed 1 Bath – Middle Floor Apartment - Sakstons source image" }],
    description: "This contemporary, well finished and pet friendly (cats and dogs) ground floor apartment features two bedrooms with built in cupboards, tiled flooring and two bathrooms one being an en-suite to the main, an open plan kitchen with Caesar stone counter tops, there is space for an upright fridge, tumble dryer and washing ",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 75,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18722',
    slug: "sakstons-the-atrium-two-bedroom-one-bathroom-apartment",
    purpose: "To rent",
    title: "The Atrium- Two Bedroom, One Bathroom Apartment",
    location: "Rivonia, Sandton",
    suburb: "Rivonia",
    city: "Sandton",
    province: "Gauteng",
    price: "R 12 000 pm",
    priceValue: 12000,
    beds: 2,
    baths: 1,
    parking: 2,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/property-9260685-19449718_sd.jpg", alt: "The Atrium- Two Bedroom, One Bathroom Apartment - Sakstons source image" }],
    description: "Spacious and modern middle floor apartment, featuring two bedrooms with built in cupboards and laminated flooring, one full bathroom (consisting of a bath/shower, basin and toilet), open plan kitchen leading into an open plan dining and lounge area, which in turn leads to a private and spacious balcony with stunning vi",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 100,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18702',
    slug: "sakstons-rental-three-bedroom-three-bathroom-house-in-westdene",
    purpose: "To rent",
    title: "Rental: Three Bedroom Three Bathroom House In Westdene",
    location: "Westdene, Johannesburg",
    suburb: "Westdene",
    city: "Johannesburg",
    province: "Gauteng",
    price: "R 22 000 pm",
    priceValue: 22000,
    beds: 3,
    baths: 3,
    parking: 3,
    type: "House",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/property-4766263-76699394_sd.jpg", alt: "Rental: Three Bedroom Three Bathroom House In Westdene - Sakstons source image" }],
    description: "This newly renovated double storey house is situated in a quiet and secure road in Westdene. An entertainers dream. Pefectly located close to the freeway, public transport (Rea Vaya line), Melville, Campus Square, Westdene dam and parks, it is in close proximity to UJ, SABC, Helen Joseph Hospital & 5 km from Wits Unive",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 205,
    erfSize: 745,
    featured: false,
  },
  {
    id: 'sakstons-18680',
    slug: "sakstons-rental-fully-furnished-two-bedroom-one-bathroom-garden-apartment-in-rivonia",
    purpose: "To rent",
    title: "Rental: Fully Furnished Two Bedroom One Bathroom Garden Apartment In Rivonia",
    location: "Rivonia, Sandton",
    suburb: "Rivonia",
    city: "Sandton",
    province: "Gauteng",
    price: "R 12 500 pm",
    priceValue: 12500,
    beds: 2,
    baths: 1,
    parking: 1,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/20230127_144712_resized.jpg", alt: "Rental: Fully Furnished Two Bedroom One Bathroom Garden Apartment In Rivonia - Sakstons source image" }],
    description: "This fully furnished two bedroom one bathroom ground floor apartment is situated in the well managed and popular complex of The Willows. Perfectly located close to all amenities and freeway. The complex has a communal swimming pool and braai facilities. Fully Furnished Two bedrooms with build in cupboards and carpeted ",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 100,
    erfSize: 110,
    featured: false,
  },
  {
    id: 'sakstons-18659',
    slug: "sakstons-cedar-acres-estate-three-bedroom-two-bathroom-middle-floor-apartment",
    purpose: "To rent",
    title: "Cedar Acres Estate- Three Bedroom, Two Bathroom Middle Floor Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 11 000 pm",
    priceValue: 11000,
    beds: 3,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Graham Donald",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/1-2.jpg", alt: "Cedar Acres Estate- Three Bedroom, Two Bathroom Middle Floor Apartment - Sakstons source image" }],
    description: "This Beautiful middle floor apartment in a sought-after complex features three bedrooms and two bathrooms , an open plan kitchen has space for two undercounter appliance and an upright fridge, spacious lounge area. The apartment is fibre internet ready and has two undercover parkings. The complex features 24-hour acces",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 107,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18581',
    slug: "sakstons-the-kanyin-2-bed-1-bath-middle-floor-apartment",
    purpose: "For sale",
    title: "The Kanyin – 2 Bed 1 Bath – Middle Floor Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 1 100 000",
    priceValue: 1100000,
    beds: 2,
    baths: 1,
    parking: 2,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/1-Capture-1.jpg", alt: "The Kanyin – 2 Bed 1 Bath – Middle Floor Apartment - Sakstons source image" }],
    description: "The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in Braai. • KITCHEN: Open plan, granite tops, plenty of built-in cupbo",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 90,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18569',
    slug: "sakstons-rental-four-bedroom-four-bathrooms-fully-furnished-apartment-in-strathavon",
    purpose: "To rent",
    title: "Rental: Four Bedroom, Four Bathrooms Fully Furnished Apartment in Strathavon.",
    location: "Strathavon, Sandton",
    suburb: "Strathavon",
    city: "Sandton",
    province: "Gauteng",
    price: "R 40 000 pm",
    priceValue: 40000,
    beds: 4,
    baths: 4,
    parking: 2,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/property-6585481-37402327_sd-2.jpg", alt: "Rental: Four Bedroom, Four Bathrooms Fully Furnished Apartment in Strathavon. - Sakstons source image" }],
    description: "This spacious and elegantly furnished double storey apartment is situated in the beautiful Forest Sandown. It has four spacious bedrooms and three bathrooms. Perfectly located close to all amenities and freeway. The complex is surrounded by nature giving a tranquil feeling. Fully Furnished Maximum of 7 people can occup",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 266,
    erfSize: 466,
    featured: false,
  },
  {
    id: 'sakstons-18534',
    slug: "sakstons-rental-two-bedroom-two-bathrooms-fully-furnished-apartment-in-strathavon-2",
    purpose: "To rent",
    title: "Rental: Two Bedroom, Two Bathrooms Fully Furnished Apartment in Strathavon.",
    location: "Strathavon, Sandton",
    suburb: "Strathavon",
    city: "Sandton",
    province: "Gauteng",
    price: "R 22 000 pm",
    priceValue: 22000,
    beds: 2,
    baths: 0,
    parking: 1,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/property-7369469-15096636_sd.jpg", alt: "Rental: Two Bedroom, Two Bathrooms Fully Furnished Apartment in Strathavon. - Sakstons source image" }],
    description: "This spacious and beautifully furnished apartment is situated in the beautiful Forest Sandown. It has two spacious bedrooms and two bathrooms. Perfectly located close to all amenities and freeway. The complex is surrounded by nature giving a tranquil feeling. Fully Furnished Beautiful kitchen ample cupboard space and i",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 160,
    erfSize: 160,
    featured: false,
  },
  {
    id: 'sakstons-18518',
    slug: "sakstons-rental-two-bedroom-two-bathrooms-fully-furnished-apartment-in-strathavon",
    purpose: "To rent",
    title: "Rental: Two Bedroom, Two Bathrooms Fully Furnished Apartment in Strathavon.",
    location: "Strathavon, Sandton",
    suburb: "Strathavon",
    city: "Sandton",
    province: "Gauteng",
    price: "R 24 000 pm",
    priceValue: 24000,
    beds: 2,
    baths: 2,
    parking: 1,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/property-6585481-37402327_sd-1.jpg", alt: "Rental: Two Bedroom, Two Bathrooms Fully Furnished Apartment in Strathavon. - Sakstons source image" }],
    description: "This spacious and elegantly furnished luxury apartment is situated in the beautiful Forest Sandown. It has two spacious bedrooms and two bathrooms. Perfectly located close to all amenities and freeway. The complex is surrounded by nature giving a tranquil feeling. Fully Furnished Beautiful kitchen ample cupboard space ",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 168,
    erfSize: 238,
    featured: false,
  },
  {
    id: 'sakstons-18478',
    slug: "sakstons-marina-vista-one-bedroom-one-bathroom-apartment",
    purpose: "To rent",
    title: "Marina Vista- One Bedroom, One Bathroom Apartment",
    location: "Parkmore, Sandton",
    suburb: "Parkmore",
    city: "Sandton",
    province: "Gauteng",
    price: "R 12 000 pm",
    priceValue: 12000,
    beds: 1,
    baths: 1,
    parking: 1,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Graham Donald",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/1-1.jpg", alt: "Marina Vista- One Bedroom, One Bathroom Apartment - Sakstons source image" }],
    description: "This Beautiful newly Renovated apartment perfectly located in a sought-after complex features one bedroom with a walk-in closet and one en suite bathroom, an open plan Dining room and lounge leading onto a spacious balcony, kitchen with space for one undercounter appliance and an upright fridge. The apartment is fibre ",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 67,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18491',
    slug: "sakstons-rental-four-bedroom-four-bathrooms-fully-furnished-cluster-in-sandown",
    purpose: "To rent",
    title: "Rental: Four Bedroom, Four Bathrooms Fully Furnished Cluster in Sandown.",
    location: "Sandown, Sandton",
    suburb: "Sandown",
    city: "Sandton",
    province: "Gauteng",
    price: "R 40 000 pm",
    priceValue: 40000,
    beds: 4,
    baths: 4,
    parking: 2,
    type: "Cluster",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/property-7364793-45943743_sd.jpg", alt: "Rental: Four Bedroom, Four Bathrooms Fully Furnished Cluster in Sandown. - Sakstons source image" }],
    description: "This spacious and beautifully furnished cluster is situated in the beautiful Royal Sandown. It has four spacious bedrooms, four en-suite bathrooms and a stunning indoor pool. Perfectly located close to all amenities and freeway. Very safe and secure. Fully Furnished Beautiful kitchen with separate scullery and pantry D",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 480,
    erfSize: 560,
    featured: false,
  },
  {
    id: 'sakstons-18457',
    slug: "sakstons-rental-four-bedroom-three-bathroom-fully-furnished-apartment-in-strathavon",
    purpose: "To rent",
    title: "Rental: Four Bedroom, Three Bathroom Fully Furnished Apartment in Strathavon.",
    location: "Strathavon, Sandton",
    suburb: "Strathavon",
    city: "Sandton",
    province: "Gauteng",
    price: "R 30 000 pm",
    priceValue: 30000,
    beds: 4,
    baths: 3,
    parking: 1,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/property-6585481-37402327_sd.jpg", alt: "Rental: Four Bedroom, Three Bathroom Fully Furnished Apartment in Strathavon. - Sakstons source image" }],
    description: "This spacious and elegantly furnished double storey apartment is situated in the beautiful Forest Sandown. It has four spacious bedrooms and three bathrooms. Perfectly located close to all amenities and freeway. The complex is surrounded by nature giving a tranquil feeling. Fully Furnished Maximum of 7 people can occup",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 185,
    erfSize: 228,
    featured: false,
  },
  {
    id: 'sakstons-18196',
    slug: "sakstons-the-kanyin-2-bed-2-bath-garden-apartment",
    purpose: "To rent",
    title: "The Kanyin – 2 Bed 2 Bath – Garden Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 11 000 pm",
    priceValue: 11000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/01.-2.jpg", alt: "The Kanyin – 2 Bed 2 Bath – Garden Apartment - Sakstons source image" }],
    description: "The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in braai and pet friendly garden. • KITCHEN: Open plan, granite tops, ",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 91,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18182',
    slug: "sakstons-the-kanyin-1-bed-1-bath-top-floor-apartment",
    purpose: "For sale",
    title: "The Kanyin – 1 Bed 1 Bath – Top Floor Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 900 000",
    priceValue: 900000,
    beds: 1,
    baths: 1,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/01.-1.jpg", alt: "The Kanyin – 1 Bed 1 Bath – Top Floor Apartment - Sakstons source image" }],
    description: "The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in Braai. • KITCHEN: Open plan, granite tops, plenty of built-in cupbo",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 60,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18165',
    slug: "sakstons-the-kanyin-2-bed-2-bath-middle-floor-apartment",
    purpose: "To rent",
    title: "The Kanyin – 2 Bed 2 Bath – Middle Floor Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 10 000 pm",
    priceValue: 10000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/Capture-1.jpg", alt: "The Kanyin – 2 Bed 2 Bath – Middle Floor Apartment - Sakstons source image" }],
    description: "The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in Braai. • KITCHEN: Open plan, granite tops, plenty of built-in cupbo",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 91,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-18038',
    slug: "sakstons-the-matrix-one-bedroom-one-bathroom-middle-apartment",
    purpose: "To rent",
    title: "THE MATRIX – One Bedroom, One Bathroom MIDDLE Apartment",
    location: "Paulshof, Sandton",
    suburb: "Paulshof",
    city: "Sandton",
    province: "Gauteng",
    price: "R 6 800 pm",
    priceValue: 6800,
    beds: 1,
    baths: 1,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Liz Marx",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/01-13.jpg", alt: "THE MATRIX – One Bedroom, One Bathroom MIDDLE Apartment - Sakstons source image" }],
    description: "This modern and spacious open plan middle floor apartment features one bedroom with built in cupboards and carpeted flooring, one full bathroom, an open plan kitchen, leading into the dining / lounge area and a private, shaded balcony on the lower level. The lounge setup with communal DSTV connections. The apartment is",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 45,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-17698',
    slug: "sakstons-hyrdo-park-one-bedroom-one-bathroom-second-floor-apartment-2",
    purpose: "To rent",
    title: "HYRDO PARK – One Bedroom, One Bathroom SECOND FLOOR Apartment",
    location: "Sandton, Sandton",
    suburb: "Sandton",
    city: "Sandton",
    province: "Gauteng",
    price: "R 8 000 pm",
    priceValue: 8000,
    beds: 1,
    baths: 2,
    parking: 1,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Graham Donald",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/01-12.jpg", alt: "HYRDO PARK – One Bedroom, One Bathroom SECOND FLOOR Apartment - Sakstons source image" }],
    description: "This ideally located and spacious second floor open plan apartment features one bedroom with built in cupboards and tiled flooring, one full bathroom en suite and a separate guest toilet, an open plan kitchen with a space for an upright fridge and one under counter appliance, leading into the dining / lounge area and a",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 54,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-17613',
    slug: "sakstons-the-william-two-bedroom-and-two-bathroom-second-floor-apartment",
    purpose: "To rent",
    title: "THE WILLIAM – Two Bedroom and Two Bathroom SECOND FLOOR Apartment",
    location: "Midrand, Midrand",
    suburb: "Midrand",
    city: "Midrand",
    province: "Gauteng",
    price: "R 9 000 pm",
    priceValue: 9000,
    beds: 2,
    baths: 2,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Graham Donald",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/01-7.jpg", alt: "THE WILLIAM – Two Bedroom and Two Bathroom SECOND FLOOR Apartment - Sakstons source image" }],
    description: "This contemporary, well finished and pet friendly (cats only, no dogs) second floor apartment features two bedroom’s with built in cupboards, tiled flooring, an en suite bathroom off the main bedroom, one full guest bathroom, an open plan kitchen with Caesar stone counter tops, a gas hob, an upright fridge, dishwasher,",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 85,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-17521',
    slug: "sakstons-the-kanyin-3-bed-2-bath-loft-apartment",
    purpose: "To rent",
    title: "The Kanyin – 3 Bed 2 Bath – Loft Apartment",
    location: "Sunninghill, Sandton",
    suburb: "Sunninghill",
    city: "Sandton",
    province: "Gauteng",
    price: "R 1 550 000 pm",
    priceValue: 1550000,
    beds: 3,
    baths: 2,
    parking: 2,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/Capture.jpg", alt: "The Kanyin – 3 Bed 2 Bath – Loft Apartment - Sakstons source image" }],
    description: "3 Bed 2 Bath – Loft Apartment The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in Braai. • LOFT: Large loft area upstai",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 150,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-17497',
    slug: "sakstons-hydra-complex-wilgeheuwel",
    purpose: "To rent",
    title: "Hydra Complex – 2 Bed 1 Bath – Townhouse – Wilgeheuwel",
    location: "Roodepoort, Roodepoort",
    suburb: "Roodepoort",
    city: "Roodepoort",
    province: "Gauteng",
    price: "R 8 000 pm",
    priceValue: 8000,
    beds: 2,
    baths: 1,
    parking: 0,
    type: "House",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/Capture1.jpg", alt: "Hydra Complex – 2 Bed 1 Bath – Townhouse – Wilgeheuwel - Sakstons source image" }],
    description: "Perfectly positioned close to all the good schools and shopping malls. Offering 2 bedrooms 1 full bathroom, Open plan tiled kitchen and lounge and large pet friendly garden. Double garage.",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 85,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-17435',
    slug: "sakstons-the-william-1-bed-1-bath-top-floor-apartment",
    purpose: "To rent",
    title: "The William – 1 Bed 1 Bath – Top Floor Apartment",
    location: "Fourways, Midrand",
    suburb: "Fourways",
    city: "Midrand",
    province: "Gauteng",
    price: "R 7 000 pm",
    priceValue: 7000,
    beds: 1,
    baths: 1,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Graham Donald",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/1.jpg", alt: "The William – 1 Bed 1 Bath – Top Floor Apartment - Sakstons source image" }],
    description: "Situated in the secure and sought-after complex of The William in Dainfern, this modern apartment features one bedroom with built in cupboards and one bathroom, an open plan kitchen featuring an electric hob. Leading into the dining and lounge areas. A small balcony runs the length of the apartment, with direct access ",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 45,
    erfSize: undefined,
    featured: false,
  },
  {
    id: 'sakstons-17328',
    slug: "sakstons-the-kanyin-2-bed-1-bath-garden-apartment-2",
    purpose: "To rent",
    title: "The Kanyin – 2 Bed 1 Bath – Garden Apartment",
    location: "Sunninghill, Sandton",
    suburb: "Sunninghill",
    city: "Sandton",
    province: "Gauteng",
    price: "R 10 500 pm",
    priceValue: 10500,
    beds: 2,
    baths: 1,
    parking: 0,
    type: "Apartment",
    agency: 'Sakstons',
    agent: "Mark Chait",
    gradient: 'from-[#1A1A2E] via-[#4A3AFF] to-[#60A5FA]',
    photos: [{ src: "https://www.sakstons.com/wp-content/uploads/2023/01/01..jpg", alt: "The Kanyin – 2 Bed 1 Bath – Garden Apartment - Sakstons source image" }],
    description: "The Kanyin boasts: a Clubhouse, a Fully Equipped Gym, Entertaining Area, Swimming Pool, Squash Courts, A Creche and 24 Hour Security. DESCRIPTION: • LOUNGE: Open plan spacious tiled with a sliding door leading out to the covered balcony with a built-in Braai and pet friendly garden • KITCHEN: Open plan, granite tops, p",
    features: ["Sakstons source listing", "Verified agency route", "POPIA-ready enquiry", "Address captured from source"],
    highlights: ['Sakstons source stock', 'Live agency starter inventory', 'Agent-routed enquiry'],
    mandate: 'Agency verified',
    listedAt: '2026-05-21',
    floorSize: 90,
    erfSize: undefined,
    featured: false,
  }
] satisfies Listing[];

export const sakstonsListings: Listing[] = sakstonsListingSeed.map((listing) => ({ ...listing, isActive: true }));
